/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *openAct;
    QAction *printAct;
    QAction *exitAct;
    QAction *zoomInAct;
    QAction *zoomOutAct;
    QAction *fitToWindowAct;
    QAction *normalSizeAct;
    QAction *aboutAct;
    QAction *aboutQtAct;
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *task1;
    QPushButton *btnTask1_01;
    QSlider *sliderTask1_01;
    QLabel *lblTask1_01;
    QWidget *task2;
    QSlider *sliderTask2_01;
    QSlider *sliderTask2_02;
    QLabel *lblHistogrammTask2_01;
    QLabel *lblHistogrammTask2_02;
    QLabel *lblTask2_01;
    QLabel *lblTask2_02;
    QLabel *lblTask2_03;
    QLabel *lblTask2_04;
    QPushButton *btnTask2_02;
    QDoubleSpinBox *dSpinBoxTask2_01;
    QDoubleSpinBox *dSpinBoxTask2_02;
    QLabel *lblTask2_05;
    QLabel *lblTask2_06;
    QPushButton *btnTask2_01;
    QLabel *lblTask2_07;
    QWidget *task3;
    QLabel *lblHistogrammTask3_02;
    QLabel *lblHistogrammTask3_01;
    QLabel *lblTask3_03;
    QLabel *lblTask3_02;
    QPushButton *btnTask3_01;
    QPushButton *btnTask3_02;
    QPushButton *btnTask3_03;
    QSpinBox *spinBoxTask3_01;
    QLabel *lblTask3_01;
    QWidget *task4;
    QTableWidget *tableTask4_01;
    QSpinBox *spinBoxTask4_01;
    QLabel *label;
    QPushButton *btnTask4_01;
    QPushButton *btnTask4_02;
    QPushButton *btnTask4_03;
    QPushButton *btnTask4_04;
    QWidget *task5;
    QPushButton *btnTask5_01;
    QDoubleSpinBox *dSpinBoxTask5_02;
    QDoubleSpinBox *dSpinBoxTask5_01;
    QLabel *label_2;
    QLabel *label_3;
    QDoubleSpinBox *dSpinBoxTask5_03;
    QSpinBox *spinBoxTask5_01;
    QLabel *label_4;
    QLabel *label_5;
    QDoubleSpinBox *dSpinBoxTask5_05;
    QDoubleSpinBox *dSpinBoxTask5_04;
    QSpinBox *spinBoxTask5_02;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QPushButton *btnTask5_02;
    QWidget *task6;
    QPushButton *btnTask6_01;
    QDoubleSpinBox *dSpinBoxTask6_02;
    QDoubleSpinBox *dSpinBoxTask6_01;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QSpinBox *spinBoxTask6_01;
    QSpinBox *spinBoxTask6_02;
    QLabel *label_12;
    QLabel *label_13;
    QScrollArea *scrollArea;
    QWidget *scrollAreaWidgetContents;
    QLabel *imageLabel;
    QTextEdit *logBrowser;
    QMenuBar *menuBar;
    QMenu *fileMenu;
    QMenu *viewMenu;
    QMenu *helpMenu;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1348, 946);
        openAct = new QAction(MainWindow);
        openAct->setObjectName(QStringLiteral("openAct"));
        printAct = new QAction(MainWindow);
        printAct->setObjectName(QStringLiteral("printAct"));
        exitAct = new QAction(MainWindow);
        exitAct->setObjectName(QStringLiteral("exitAct"));
        zoomInAct = new QAction(MainWindow);
        zoomInAct->setObjectName(QStringLiteral("zoomInAct"));
        zoomOutAct = new QAction(MainWindow);
        zoomOutAct->setObjectName(QStringLiteral("zoomOutAct"));
        fitToWindowAct = new QAction(MainWindow);
        fitToWindowAct->setObjectName(QStringLiteral("fitToWindowAct"));
        normalSizeAct = new QAction(MainWindow);
        normalSizeAct->setObjectName(QStringLiteral("normalSizeAct"));
        aboutAct = new QAction(MainWindow);
        aboutAct->setObjectName(QStringLiteral("aboutAct"));
        aboutQtAct = new QAction(MainWindow);
        aboutQtAct->setObjectName(QStringLiteral("aboutQtAct"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(10, 10, 521, 731));
        task1 = new QWidget();
        task1->setObjectName(QStringLiteral("task1"));
        btnTask1_01 = new QPushButton(task1);
        btnTask1_01->setObjectName(QStringLiteral("btnTask1_01"));
        btnTask1_01->setGeometry(QRect(150, 210, 171, 41));
        sliderTask1_01 = new QSlider(task1);
        sliderTask1_01->setObjectName(QStringLiteral("sliderTask1_01"));
        sliderTask1_01->setGeometry(QRect(150, 170, 171, 22));
        sliderTask1_01->setOrientation(Qt::Horizontal);
        lblTask1_01 = new QLabel(task1);
        lblTask1_01->setObjectName(QStringLiteral("lblTask1_01"));
        lblTask1_01->setGeometry(QRect(165, 150, 141, 16));
        tabWidget->addTab(task1, QString());
        task2 = new QWidget();
        task2->setObjectName(QStringLiteral("task2"));
        sliderTask2_01 = new QSlider(task2);
        sliderTask2_01->setObjectName(QStringLiteral("sliderTask2_01"));
        sliderTask2_01->setGeometry(QRect(90, 270, 311, 22));
        sliderTask2_01->setValue(50);
        sliderTask2_01->setOrientation(Qt::Horizontal);
        sliderTask2_02 = new QSlider(task2);
        sliderTask2_02->setObjectName(QStringLiteral("sliderTask2_02"));
        sliderTask2_02->setGeometry(QRect(90, 320, 311, 22));
        sliderTask2_02->setValue(50);
        sliderTask2_02->setOrientation(Qt::Horizontal);
        lblHistogrammTask2_01 = new QLabel(task2);
        lblHistogrammTask2_01->setObjectName(QStringLiteral("lblHistogrammTask2_01"));
        lblHistogrammTask2_01->setGeometry(QRect(0, 40, 256, 121));
        lblHistogrammTask2_01->setAutoFillBackground(true);
        lblHistogrammTask2_02 = new QLabel(task2);
        lblHistogrammTask2_02->setObjectName(QStringLiteral("lblHistogrammTask2_02"));
        lblHistogrammTask2_02->setGeometry(QRect(260, 40, 256, 121));
        lblHistogrammTask2_02->setAutoFillBackground(true);
        lblTask2_01 = new QLabel(task2);
        lblTask2_01->setObjectName(QStringLiteral("lblTask2_01"));
        lblTask2_01->setGeometry(QRect(90, 10, 61, 16));
        lblTask2_02 = new QLabel(task2);
        lblTask2_02->setObjectName(QStringLiteral("lblTask2_02"));
        lblTask2_02->setGeometry(QRect(310, 10, 121, 16));
        lblTask2_03 = new QLabel(task2);
        lblTask2_03->setObjectName(QStringLiteral("lblTask2_03"));
        lblTask2_03->setGeometry(QRect(200, 240, 91, 16));
        lblTask2_04 = new QLabel(task2);
        lblTask2_04->setObjectName(QStringLiteral("lblTask2_04"));
        lblTask2_04->setGeometry(QRect(200, 300, 91, 16));
        btnTask2_02 = new QPushButton(task2);
        btnTask2_02->setObjectName(QStringLiteral("btnTask2_02"));
        btnTask2_02->setGeometry(QRect(130, 520, 231, 61));
        dSpinBoxTask2_01 = new QDoubleSpinBox(task2);
        dSpinBoxTask2_01->setObjectName(QStringLiteral("dSpinBoxTask2_01"));
        dSpinBoxTask2_01->setGeometry(QRect(290, 460, 62, 22));
        dSpinBoxTask2_01->setDecimals(3);
        dSpinBoxTask2_01->setValue(0.5);
        dSpinBoxTask2_02 = new QDoubleSpinBox(task2);
        dSpinBoxTask2_02->setObjectName(QStringLiteral("dSpinBoxTask2_02"));
        dSpinBoxTask2_02->setGeometry(QRect(290, 490, 62, 22));
        dSpinBoxTask2_02->setDecimals(3);
        dSpinBoxTask2_02->setValue(0.5);
        lblTask2_05 = new QLabel(task2);
        lblTask2_05->setObjectName(QStringLiteral("lblTask2_05"));
        lblTask2_05->setGeometry(QRect(240, 465, 47, 13));
        lblTask2_06 = new QLabel(task2);
        lblTask2_06->setObjectName(QStringLiteral("lblTask2_06"));
        lblTask2_06->setGeometry(QRect(240, 495, 47, 13));
        btnTask2_01 = new QPushButton(task2);
        btnTask2_01->setObjectName(QStringLiteral("btnTask2_01"));
        btnTask2_01->setGeometry(QRect(130, 360, 231, 41));
        lblTask2_07 = new QLabel(task2);
        lblTask2_07->setObjectName(QStringLiteral("lblTask2_07"));
        lblTask2_07->setGeometry(QRect(95, 410, 301, 21));
        lblTask2_07->setAutoFillBackground(true);
        lblTask2_07->setAlignment(Qt::AlignCenter);
        tabWidget->addTab(task2, QString());
        task3 = new QWidget();
        task3->setObjectName(QStringLiteral("task3"));
        lblHistogrammTask3_02 = new QLabel(task3);
        lblHistogrammTask3_02->setObjectName(QStringLiteral("lblHistogrammTask3_02"));
        lblHistogrammTask3_02->setGeometry(QRect(260, 40, 256, 121));
        lblHistogrammTask3_02->setAutoFillBackground(true);
        lblHistogrammTask3_01 = new QLabel(task3);
        lblHistogrammTask3_01->setObjectName(QStringLiteral("lblHistogrammTask3_01"));
        lblHistogrammTask3_01->setGeometry(QRect(0, 40, 256, 121));
        lblHistogrammTask3_01->setAutoFillBackground(true);
        lblTask3_03 = new QLabel(task3);
        lblTask3_03->setObjectName(QStringLiteral("lblTask3_03"));
        lblTask3_03->setGeometry(QRect(310, 10, 121, 16));
        lblTask3_02 = new QLabel(task3);
        lblTask3_02->setObjectName(QStringLiteral("lblTask3_02"));
        lblTask3_02->setGeometry(QRect(90, 10, 61, 16));
        btnTask3_01 = new QPushButton(task3);
        btnTask3_01->setObjectName(QStringLiteral("btnTask3_01"));
        btnTask3_01->setGeometry(QRect(145, 190, 201, 51));
        btnTask3_02 = new QPushButton(task3);
        btnTask3_02->setObjectName(QStringLiteral("btnTask3_02"));
        btnTask3_02->setGeometry(QRect(75, 260, 351, 41));
        btnTask3_03 = new QPushButton(task3);
        btnTask3_03->setObjectName(QStringLiteral("btnTask3_03"));
        btnTask3_03->setGeometry(QRect(75, 420, 351, 41));
        spinBoxTask3_01 = new QSpinBox(task3);
        spinBoxTask3_01->setObjectName(QStringLiteral("spinBoxTask3_01"));
        spinBoxTask3_01->setGeometry(QRect(380, 380, 42, 22));
        spinBoxTask3_01->setValue(40);
        lblTask3_01 = new QLabel(task3);
        lblTask3_01->setObjectName(QStringLiteral("lblTask3_01"));
        lblTask3_01->setGeometry(QRect(260, 382, 121, 16));
        tabWidget->addTab(task3, QString());
        task4 = new QWidget();
        task4->setObjectName(QStringLiteral("task4"));
        tableTask4_01 = new QTableWidget(task4);
        if (tableTask4_01->columnCount() < 7)
            tableTask4_01->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableTask4_01->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableTask4_01->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableTask4_01->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableTask4_01->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableTask4_01->setHorizontalHeaderItem(4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableTask4_01->setHorizontalHeaderItem(5, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableTask4_01->setHorizontalHeaderItem(6, __qtablewidgetitem6);
        if (tableTask4_01->rowCount() < 7)
            tableTask4_01->setRowCount(7);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableTask4_01->setVerticalHeaderItem(0, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableTask4_01->setVerticalHeaderItem(1, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableTask4_01->setVerticalHeaderItem(2, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableTask4_01->setVerticalHeaderItem(3, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableTask4_01->setVerticalHeaderItem(4, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableTask4_01->setVerticalHeaderItem(5, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableTask4_01->setVerticalHeaderItem(6, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableTask4_01->setItem(0, 0, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableTask4_01->setItem(0, 1, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        tableTask4_01->setItem(0, 2, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tableTask4_01->setItem(0, 3, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        tableTask4_01->setItem(0, 4, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tableTask4_01->setItem(0, 5, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tableTask4_01->setItem(0, 6, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tableTask4_01->setItem(1, 0, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        tableTask4_01->setItem(1, 1, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        tableTask4_01->setItem(1, 2, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        tableTask4_01->setItem(1, 3, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        tableTask4_01->setItem(1, 4, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        tableTask4_01->setItem(1, 5, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        tableTask4_01->setItem(1, 6, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        tableTask4_01->setItem(2, 0, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        tableTask4_01->setItem(2, 1, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        tableTask4_01->setItem(2, 2, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        tableTask4_01->setItem(2, 3, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        tableTask4_01->setItem(2, 4, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        tableTask4_01->setItem(2, 5, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        tableTask4_01->setItem(2, 6, __qtablewidgetitem34);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        tableTask4_01->setItem(3, 0, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        tableTask4_01->setItem(3, 1, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        tableTask4_01->setItem(3, 2, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        tableTask4_01->setItem(3, 3, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        tableTask4_01->setItem(3, 4, __qtablewidgetitem39);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        tableTask4_01->setItem(3, 5, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        tableTask4_01->setItem(3, 6, __qtablewidgetitem41);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        tableTask4_01->setItem(4, 0, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        tableTask4_01->setItem(4, 1, __qtablewidgetitem43);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        tableTask4_01->setItem(4, 2, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        tableTask4_01->setItem(4, 3, __qtablewidgetitem45);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        tableTask4_01->setItem(4, 4, __qtablewidgetitem46);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        tableTask4_01->setItem(4, 5, __qtablewidgetitem47);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        tableTask4_01->setItem(4, 6, __qtablewidgetitem48);
        QTableWidgetItem *__qtablewidgetitem49 = new QTableWidgetItem();
        tableTask4_01->setItem(5, 0, __qtablewidgetitem49);
        QTableWidgetItem *__qtablewidgetitem50 = new QTableWidgetItem();
        tableTask4_01->setItem(5, 1, __qtablewidgetitem50);
        QTableWidgetItem *__qtablewidgetitem51 = new QTableWidgetItem();
        tableTask4_01->setItem(5, 2, __qtablewidgetitem51);
        QTableWidgetItem *__qtablewidgetitem52 = new QTableWidgetItem();
        tableTask4_01->setItem(5, 3, __qtablewidgetitem52);
        QTableWidgetItem *__qtablewidgetitem53 = new QTableWidgetItem();
        tableTask4_01->setItem(5, 4, __qtablewidgetitem53);
        QTableWidgetItem *__qtablewidgetitem54 = new QTableWidgetItem();
        tableTask4_01->setItem(5, 5, __qtablewidgetitem54);
        QTableWidgetItem *__qtablewidgetitem55 = new QTableWidgetItem();
        tableTask4_01->setItem(5, 6, __qtablewidgetitem55);
        QTableWidgetItem *__qtablewidgetitem56 = new QTableWidgetItem();
        tableTask4_01->setItem(6, 0, __qtablewidgetitem56);
        QTableWidgetItem *__qtablewidgetitem57 = new QTableWidgetItem();
        tableTask4_01->setItem(6, 1, __qtablewidgetitem57);
        QTableWidgetItem *__qtablewidgetitem58 = new QTableWidgetItem();
        tableTask4_01->setItem(6, 2, __qtablewidgetitem58);
        QTableWidgetItem *__qtablewidgetitem59 = new QTableWidgetItem();
        tableTask4_01->setItem(6, 3, __qtablewidgetitem59);
        QTableWidgetItem *__qtablewidgetitem60 = new QTableWidgetItem();
        tableTask4_01->setItem(6, 4, __qtablewidgetitem60);
        QTableWidgetItem *__qtablewidgetitem61 = new QTableWidgetItem();
        tableTask4_01->setItem(6, 5, __qtablewidgetitem61);
        QTableWidgetItem *__qtablewidgetitem62 = new QTableWidgetItem();
        tableTask4_01->setItem(6, 6, __qtablewidgetitem62);
        tableTask4_01->setObjectName(QStringLiteral("tableTask4_01"));
        tableTask4_01->setGeometry(QRect(20, 90, 441, 261));
        tableTask4_01->setAlternatingRowColors(true);
        tableTask4_01->setShowGrid(true);
        tableTask4_01->setGridStyle(Qt::SolidLine);
        tableTask4_01->setWordWrap(true);
        tableTask4_01->setCornerButtonEnabled(true);
        tableTask4_01->horizontalHeader()->setCascadingSectionResizes(false);
        spinBoxTask4_01 = new QSpinBox(task4);
        spinBoxTask4_01->setObjectName(QStringLiteral("spinBoxTask4_01"));
        spinBoxTask4_01->setGeometry(QRect(310, 50, 42, 22));
        spinBoxTask4_01->setMinimum(1);
        spinBoxTask4_01->setMaximum(11);
        spinBoxTask4_01->setSingleStep(2);
        spinBoxTask4_01->setValue(7);
        label = new QLabel(task4);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(160, 52, 131, 16));
        btnTask4_01 = new QPushButton(task4);
        btnTask4_01->setObjectName(QStringLiteral("btnTask4_01"));
        btnTask4_01->setGeometry(QRect(150, 370, 171, 41));
        btnTask4_02 = new QPushButton(task4);
        btnTask4_02->setObjectName(QStringLiteral("btnTask4_02"));
        btnTask4_02->setGeometry(QRect(150, 420, 171, 41));
        btnTask4_03 = new QPushButton(task4);
        btnTask4_03->setObjectName(QStringLiteral("btnTask4_03"));
        btnTask4_03->setGeometry(QRect(150, 470, 171, 41));
        btnTask4_04 = new QPushButton(task4);
        btnTask4_04->setObjectName(QStringLiteral("btnTask4_04"));
        btnTask4_04->setGeometry(QRect(150, 520, 171, 41));
        tabWidget->addTab(task4, QString());
        task5 = new QWidget();
        task5->setObjectName(QStringLiteral("task5"));
        btnTask5_01 = new QPushButton(task5);
        btnTask5_01->setObjectName(QStringLiteral("btnTask5_01"));
        btnTask5_01->setGeometry(QRect(150, 210, 161, 41));
        dSpinBoxTask5_02 = new QDoubleSpinBox(task5);
        dSpinBoxTask5_02->setObjectName(QStringLiteral("dSpinBoxTask5_02"));
        dSpinBoxTask5_02->setGeometry(QRect(250, 130, 62, 22));
        dSpinBoxTask5_02->setDecimals(3);
        dSpinBoxTask5_02->setMinimum(0);
        dSpinBoxTask5_02->setValue(55);
        dSpinBoxTask5_01 = new QDoubleSpinBox(task5);
        dSpinBoxTask5_01->setObjectName(QStringLiteral("dSpinBoxTask5_01"));
        dSpinBoxTask5_01->setGeometry(QRect(250, 170, 62, 22));
        dSpinBoxTask5_01->setDecimals(3);
        dSpinBoxTask5_01->setValue(33);
        label_2 = new QLabel(task5);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(200, 130, 51, 21));
        label_3 = new QLabel(task5);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(200, 170, 51, 21));
        dSpinBoxTask5_03 = new QDoubleSpinBox(task5);
        dSpinBoxTask5_03->setObjectName(QStringLiteral("dSpinBoxTask5_03"));
        dSpinBoxTask5_03->setGeometry(QRect(250, 90, 62, 22));
        dSpinBoxTask5_03->setMinimum(0.1);
        dSpinBoxTask5_03->setValue(3);
        spinBoxTask5_01 = new QSpinBox(task5);
        spinBoxTask5_01->setObjectName(QStringLiteral("spinBoxTask5_01"));
        spinBoxTask5_01->setGeometry(QRect(270, 50, 42, 22));
        spinBoxTask5_01->setMinimum(1);
        spinBoxTask5_01->setSingleStep(2);
        spinBoxTask5_01->setValue(3);
        label_4 = new QLabel(task5);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(200, 90, 51, 21));
        label_5 = new QLabel(task5);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(200, 50, 61, 21));
        dSpinBoxTask5_05 = new QDoubleSpinBox(task5);
        dSpinBoxTask5_05->setObjectName(QStringLiteral("dSpinBoxTask5_05"));
        dSpinBoxTask5_05->setGeometry(QRect(240, 310, 62, 22));
        dSpinBoxTask5_05->setDecimals(3);
        dSpinBoxTask5_05->setValue(3);
        dSpinBoxTask5_04 = new QDoubleSpinBox(task5);
        dSpinBoxTask5_04->setObjectName(QStringLiteral("dSpinBoxTask5_04"));
        dSpinBoxTask5_04->setGeometry(QRect(240, 340, 62, 22));
        dSpinBoxTask5_04->setMinimum(0.2);
        dSpinBoxTask5_04->setMaximum(4);
        dSpinBoxTask5_04->setValue(2);
        spinBoxTask5_02 = new QSpinBox(task5);
        spinBoxTask5_02->setObjectName(QStringLiteral("spinBoxTask5_02"));
        spinBoxTask5_02->setGeometry(QRect(260, 280, 42, 22));
        spinBoxTask5_02->setMinimum(1);
        spinBoxTask5_02->setSingleStep(2);
        label_6 = new QLabel(task5);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(190, 280, 61, 21));
        label_7 = new QLabel(task5);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(190, 310, 51, 21));
        label_8 = new QLabel(task5);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(190, 340, 51, 21));
        btnTask5_02 = new QPushButton(task5);
        btnTask5_02->setObjectName(QStringLiteral("btnTask5_02"));
        btnTask5_02->setGeometry(QRect(150, 380, 161, 41));
        tabWidget->addTab(task5, QString());
        task6 = new QWidget();
        task6->setObjectName(QStringLiteral("task6"));
        btnTask6_01 = new QPushButton(task6);
        btnTask6_01->setObjectName(QStringLiteral("btnTask6_01"));
        btnTask6_01->setGeometry(QRect(140, 250, 171, 51));
        dSpinBoxTask6_02 = new QDoubleSpinBox(task6);
        dSpinBoxTask6_02->setObjectName(QStringLiteral("dSpinBoxTask6_02"));
        dSpinBoxTask6_02->setGeometry(QRect(250, 160, 62, 22));
        dSpinBoxTask6_02->setValue(0.05);
        dSpinBoxTask6_01 = new QDoubleSpinBox(task6);
        dSpinBoxTask6_01->setObjectName(QStringLiteral("dSpinBoxTask6_01"));
        dSpinBoxTask6_01->setGeometry(QRect(250, 190, 62, 22));
        dSpinBoxTask6_01->setValue(10);
        label_9 = new QLabel(task6);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(220, 160, 47, 18));
        label_10 = new QLabel(task6);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(220, 190, 47, 13));
        label_11 = new QLabel(task6);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(170, 220, 47, 13));
        spinBoxTask6_01 = new QSpinBox(task6);
        spinBoxTask6_01->setObjectName(QStringLiteral("spinBoxTask6_01"));
        spinBoxTask6_01->setGeometry(QRect(210, 220, 101, 22));
        spinBoxTask6_01->setMaximum(10000000);
        spinBoxTask6_01->setValue(25000);
        spinBoxTask6_02 = new QSpinBox(task6);
        spinBoxTask6_02->setObjectName(QStringLiteral("spinBoxTask6_02"));
        spinBoxTask6_02->setGeometry(QRect(270, 130, 41, 22));
        spinBoxTask6_02->setMaximum(20);
        spinBoxTask6_02->setValue(4);
        label_12 = new QLabel(task6);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(180, 130, 81, 20));
        label_13 = new QLabel(task6);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(90, 50, 291, 51));
        QFont font;
        font.setPointSize(26);
        label_13->setFont(font);
        tabWidget->addTab(task6, QString());
        scrollArea = new QScrollArea(centralWidget);
        scrollArea->setObjectName(QStringLiteral("scrollArea"));
        scrollArea->setGeometry(QRect(530, 10, 801, 731));
        scrollArea->setAutoFillBackground(false);
        scrollArea->setFrameShape(QFrame::StyledPanel);
        scrollArea->setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        scrollArea->setHorizontalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        scrollArea->setWidgetResizable(true);
        scrollAreaWidgetContents = new QWidget();
        scrollAreaWidgetContents->setObjectName(QStringLiteral("scrollAreaWidgetContents"));
        scrollAreaWidgetContents->setGeometry(QRect(0, 0, 799, 729));
        scrollAreaWidgetContents->setAutoFillBackground(true);
        imageLabel = new QLabel(scrollAreaWidgetContents);
        imageLabel->setObjectName(QStringLiteral("imageLabel"));
        imageLabel->setGeometry(QRect(9, 9, 791, 721));
        QSizePolicy sizePolicy(QSizePolicy::Ignored, QSizePolicy::Ignored);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(imageLabel->sizePolicy().hasHeightForWidth());
        imageLabel->setSizePolicy(sizePolicy);
        imageLabel->setScaledContents(true);
        scrollArea->setWidget(scrollAreaWidgetContents);
        logBrowser = new QTextEdit(centralWidget);
        logBrowser->setObjectName(QStringLiteral("logBrowser"));
        logBrowser->setGeometry(QRect(10, 760, 1321, 121));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1348, 21));
        fileMenu = new QMenu(menuBar);
        fileMenu->setObjectName(QStringLiteral("fileMenu"));
        viewMenu = new QMenu(menuBar);
        viewMenu->setObjectName(QStringLiteral("viewMenu"));
        helpMenu = new QMenu(menuBar);
        helpMenu->setObjectName(QStringLiteral("helpMenu"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(fileMenu->menuAction());
        menuBar->addAction(viewMenu->menuAction());
        menuBar->addAction(helpMenu->menuAction());
        fileMenu->addAction(openAct);
        fileMenu->addAction(printAct);
        fileMenu->addSeparator();
        fileMenu->addAction(exitAct);
        viewMenu->addAction(zoomInAct);
        viewMenu->addAction(zoomOutAct);
        viewMenu->addAction(normalSizeAct);
        viewMenu->addSeparator();
        viewMenu->addAction(fitToWindowAct);
        helpMenu->addAction(aboutAct);
        helpMenu->addAction(aboutQtAct);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Computergrafik 2", Q_NULLPTR));
        openAct->setText(QApplication::translate("MainWindow", "Open", Q_NULLPTR));
        printAct->setText(QApplication::translate("MainWindow", "Print", Q_NULLPTR));
        exitAct->setText(QApplication::translate("MainWindow", "Exit", Q_NULLPTR));
        zoomInAct->setText(QApplication::translate("MainWindow", "Zoom In (25%)", Q_NULLPTR));
        zoomOutAct->setText(QApplication::translate("MainWindow", "Zoom Out (25%)", Q_NULLPTR));
        fitToWindowAct->setText(QApplication::translate("MainWindow", "Fit to window", Q_NULLPTR));
        normalSizeAct->setText(QApplication::translate("MainWindow", "Normal Size", Q_NULLPTR));
        aboutAct->setText(QApplication::translate("MainWindow", "About", Q_NULLPTR));
        aboutQtAct->setText(QApplication::translate("MainWindow", "About Qt", Q_NULLPTR));
        btnTask1_01->setText(QApplication::translate("MainWindow", "Rotes Kreuz malen", Q_NULLPTR));
        lblTask1_01->setText(QApplication::translate("MainWindow", "Gr\303\266\303\237e des Kreuzes einstellen", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(task1), QApplication::translate("MainWindow", "Aufgabe 1", Q_NULLPTR));
        lblHistogrammTask2_01->setText(QString());
        lblHistogrammTask2_02->setText(QString());
        lblTask2_01->setText(QApplication::translate("MainWindow", "Historgramm", Q_NULLPTR));
        lblTask2_02->setText(QApplication::translate("MainWindow", "Kumulatives Histogramm", Q_NULLPTR));
        lblTask2_03->setText(QApplication::translate("MainWindow", "Helligkeit einstellen", Q_NULLPTR));
        lblTask2_04->setText(QApplication::translate("MainWindow", "Kontrast anpassen", Q_NULLPTR));
        btnTask2_02->setText(QApplication::translate("MainWindow", "Automatische robuste Kontrastanpassung", Q_NULLPTR));
        lblTask2_05->setText(QApplication::translate("MainWindow", "Minimum:", Q_NULLPTR));
        lblTask2_06->setText(QApplication::translate("MainWindow", "Minimum:", Q_NULLPTR));
        btnTask2_01->setText(QApplication::translate("MainWindow", "Mittlere Helligkeit und Varianz berechnen", Q_NULLPTR));
        lblTask2_07->setText(QApplication::translate("MainWindow", "noch nicht berechnet", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(task2), QApplication::translate("MainWindow", "Aufgabe 2", Q_NULLPTR));
        lblHistogrammTask3_02->setText(QString());
        lblHistogrammTask3_01->setText(QString());
        lblTask3_03->setText(QApplication::translate("MainWindow", "Kumulatives Histogramm", Q_NULLPTR));
        lblTask3_02->setText(QApplication::translate("MainWindow", "Historgramm", Q_NULLPTR));
        btnTask3_01->setText(QApplication::translate("MainWindow", "Linearen Ausgleich anwenden", Q_NULLPTR));
        btnTask3_02->setText(QApplication::translate("MainWindow", "Referenz laden und st\303\274ckweisen linearen Ausgleichen vornehmen", Q_NULLPTR));
        btnTask3_03->setText(QApplication::translate("MainWindow", "Gau\303\237 als Referenz benutzen um sukzessiv Aufzuf\303\274llen", Q_NULLPTR));
        lblTask3_01->setText(QApplication::translate("MainWindow", "Gau\303\237 Verteilung \303\244ndern", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(task3), QApplication::translate("MainWindow", "Aufgabe3", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem = tableTask4_01->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("MainWindow", "1", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem1 = tableTask4_01->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem2 = tableTask4_01->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem3 = tableTask4_01->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem4 = tableTask4_01->horizontalHeaderItem(4);
        ___qtablewidgetitem4->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem5 = tableTask4_01->horizontalHeaderItem(5);
        ___qtablewidgetitem5->setText(QApplication::translate("MainWindow", "6", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem6 = tableTask4_01->horizontalHeaderItem(6);
        ___qtablewidgetitem6->setText(QApplication::translate("MainWindow", "7", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem7 = tableTask4_01->verticalHeaderItem(0);
        ___qtablewidgetitem7->setText(QApplication::translate("MainWindow", "1", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem8 = tableTask4_01->verticalHeaderItem(1);
        ___qtablewidgetitem8->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem9 = tableTask4_01->verticalHeaderItem(2);
        ___qtablewidgetitem9->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem10 = tableTask4_01->verticalHeaderItem(3);
        ___qtablewidgetitem10->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem11 = tableTask4_01->verticalHeaderItem(4);
        ___qtablewidgetitem11->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem12 = tableTask4_01->verticalHeaderItem(5);
        ___qtablewidgetitem12->setText(QApplication::translate("MainWindow", "6", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem13 = tableTask4_01->verticalHeaderItem(6);
        ___qtablewidgetitem13->setText(QApplication::translate("MainWindow", "7", Q_NULLPTR));

        const bool __sortingEnabled = tableTask4_01->isSortingEnabled();
        tableTask4_01->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem14 = tableTask4_01->item(0, 0);
        ___qtablewidgetitem14->setText(QApplication::translate("MainWindow", "1", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem15 = tableTask4_01->item(0, 1);
        ___qtablewidgetitem15->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem16 = tableTask4_01->item(0, 2);
        ___qtablewidgetitem16->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem17 = tableTask4_01->item(0, 3);
        ___qtablewidgetitem17->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem18 = tableTask4_01->item(0, 4);
        ___qtablewidgetitem18->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem19 = tableTask4_01->item(0, 5);
        ___qtablewidgetitem19->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem20 = tableTask4_01->item(0, 6);
        ___qtablewidgetitem20->setText(QApplication::translate("MainWindow", "1", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem21 = tableTask4_01->item(1, 0);
        ___qtablewidgetitem21->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem22 = tableTask4_01->item(1, 1);
        ___qtablewidgetitem22->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem23 = tableTask4_01->item(1, 2);
        ___qtablewidgetitem23->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem24 = tableTask4_01->item(1, 3);
        ___qtablewidgetitem24->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem25 = tableTask4_01->item(1, 4);
        ___qtablewidgetitem25->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem26 = tableTask4_01->item(1, 5);
        ___qtablewidgetitem26->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem27 = tableTask4_01->item(1, 6);
        ___qtablewidgetitem27->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem28 = tableTask4_01->item(2, 0);
        ___qtablewidgetitem28->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem29 = tableTask4_01->item(2, 1);
        ___qtablewidgetitem29->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem30 = tableTask4_01->item(2, 2);
        ___qtablewidgetitem30->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem31 = tableTask4_01->item(2, 3);
        ___qtablewidgetitem31->setText(QApplication::translate("MainWindow", "6", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem32 = tableTask4_01->item(2, 4);
        ___qtablewidgetitem32->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem33 = tableTask4_01->item(2, 5);
        ___qtablewidgetitem33->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem34 = tableTask4_01->item(2, 6);
        ___qtablewidgetitem34->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem35 = tableTask4_01->item(3, 0);
        ___qtablewidgetitem35->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem36 = tableTask4_01->item(3, 1);
        ___qtablewidgetitem36->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem37 = tableTask4_01->item(3, 2);
        ___qtablewidgetitem37->setText(QApplication::translate("MainWindow", "6", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem38 = tableTask4_01->item(3, 3);
        ___qtablewidgetitem38->setText(QApplication::translate("MainWindow", "7", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem39 = tableTask4_01->item(3, 4);
        ___qtablewidgetitem39->setText(QApplication::translate("MainWindow", "6", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem40 = tableTask4_01->item(3, 5);
        ___qtablewidgetitem40->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem41 = tableTask4_01->item(3, 6);
        ___qtablewidgetitem41->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem42 = tableTask4_01->item(4, 0);
        ___qtablewidgetitem42->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem43 = tableTask4_01->item(4, 1);
        ___qtablewidgetitem43->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem44 = tableTask4_01->item(4, 2);
        ___qtablewidgetitem44->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem45 = tableTask4_01->item(4, 3);
        ___qtablewidgetitem45->setText(QApplication::translate("MainWindow", "6", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem46 = tableTask4_01->item(4, 4);
        ___qtablewidgetitem46->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem47 = tableTask4_01->item(4, 5);
        ___qtablewidgetitem47->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem48 = tableTask4_01->item(4, 6);
        ___qtablewidgetitem48->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem49 = tableTask4_01->item(5, 0);
        ___qtablewidgetitem49->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem50 = tableTask4_01->item(5, 1);
        ___qtablewidgetitem50->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem51 = tableTask4_01->item(5, 2);
        ___qtablewidgetitem51->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem52 = tableTask4_01->item(5, 3);
        ___qtablewidgetitem52->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem53 = tableTask4_01->item(5, 4);
        ___qtablewidgetitem53->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem54 = tableTask4_01->item(5, 5);
        ___qtablewidgetitem54->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem55 = tableTask4_01->item(5, 6);
        ___qtablewidgetitem55->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem56 = tableTask4_01->item(6, 0);
        ___qtablewidgetitem56->setText(QApplication::translate("MainWindow", "1", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem57 = tableTask4_01->item(6, 1);
        ___qtablewidgetitem57->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem58 = tableTask4_01->item(6, 2);
        ___qtablewidgetitem58->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem59 = tableTask4_01->item(6, 3);
        ___qtablewidgetitem59->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem60 = tableTask4_01->item(6, 4);
        ___qtablewidgetitem60->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem61 = tableTask4_01->item(6, 5);
        ___qtablewidgetitem61->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem62 = tableTask4_01->item(6, 6);
        ___qtablewidgetitem62->setText(QApplication::translate("MainWindow", "1", Q_NULLPTR));
        tableTask4_01->setSortingEnabled(__sortingEnabled);

        label->setText(QApplication::translate("MainWindow", "Gr\303\266\303\237e des Filters angeben:", Q_NULLPTR));
        btnTask4_01->setText(QApplication::translate("MainWindow", "Linearer Filter", Q_NULLPTR));
        btnTask4_02->setText(QApplication::translate("MainWindow", "Filter mit Zero Padding", Q_NULLPTR));
        btnTask4_03->setText(QApplication::translate("MainWindow", "Filter mit konstantem Rand", Q_NULLPTR));
        btnTask4_04->setText(QApplication::translate("MainWindow", "Filter mit gespiegeltem Rand", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(task4), QApplication::translate("MainWindow", "Aufgabe4", Q_NULLPTR));
        btnTask5_01->setText(QApplication::translate("MainWindow", "Canny Edge ausf\303\274hren", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "t_high", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "t_low", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "sigma", Q_NULLPTR));
        label_5->setText(QApplication::translate("MainWindow", "Size of Gau\303\237", Q_NULLPTR));
        label_6->setText(QApplication::translate("MainWindow", "Size of Gau\303\237", Q_NULLPTR));
        label_7->setText(QApplication::translate("MainWindow", "sigma", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "weight", Q_NULLPTR));
        btnTask5_02->setText(QApplication::translate("MainWindow", "USM Filter", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(task5), QApplication::translate("MainWindow", "Aufgabe5", Q_NULLPTR));
        btnTask6_01->setText(QApplication::translate("MainWindow", "Harris anweden", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "alpha", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "dmin", Q_NULLPTR));
        label_11->setText(QApplication::translate("MainWindow", "t_high", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", "radius of circles", Q_NULLPTR));
        label_13->setText(QApplication::translate("MainWindow", "Harris Algorithmus", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(task6), QApplication::translate("MainWindow", "Aufgabe6", Q_NULLPTR));
        imageLabel->setText(QString());
        fileMenu->setTitle(QApplication::translate("MainWindow", "File", Q_NULLPTR));
        viewMenu->setTitle(QApplication::translate("MainWindow", "View", Q_NULLPTR));
        helpMenu->setTitle(QApplication::translate("MainWindow", "Help", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
